### ISSUE TITLE
feature: custom 429 per limit

### ISSUE THREAD

**Issue by euri10** [abersheeran/asgi-ratelimit#19]
so far we can have a custom 429 but only one,
what would be cool is to have a custom 429 per limit, e.g.

429 "you reached your daily limit" if the daily limit is passed

however I wonder at what level this kind of config would make sense

**Comment by abersheeran** [comment]
Because 429 handler is a complete ASGI application. So as long as the current limiting information can be passed to it, a highly customized response can be achieved.
