### ISSUE TITLE
Exclude certain paths?

### ISSUE THREAD

**Issue by ahasoftware** [abersheeran/asgi-ratelimit#22]
I'm having a rather custom requirement to exclude (not count the rate limit) against certain URL paths.

For example given the endpoint
```
domain.com/api/find/:country
```

I'd like to exclude some paths then, e.g.:
```python
config={
    r"^/api/find/germany": [ # do nothing ],
    r"^/api/find/belgium": [
        Rule(minute=50, group="belgium")
    ],
    ...
}
```

I think it's not currently possible? After looking at the code.

Do you think such functionality could benefit other users?

**Comment by ahasoftware** [comment]
Me thinks this exclusion should happen [in the core module once the URL is matched](https://github.com/abersheeran/asgi-ratelimit/blob/7aec8f771eb7cd7a6ec467930030ed60227592b2/ratelimit/core.py#L46) and before it proceeds to look up user/group?

**Comment by abersheeran** [comment]
You can do it. Just like the follow code:

```python
config={
    r"^/api/find/germany": [Rule()],
    r"^/api/find/belgium": [
        Rule(minute=50, group="belgium")
    ],
    ...
}
```

Not giving any time parameter to `Rule` means that the request restriction is lifted. And, `RatelimitMiddleware` will use the first matched route, so you can use it first if you put the whitelist route in front of other routes.
