### ISSUE TITLE
About documentation

### ISSUE THREAD

**Issue by himalacharya** [abersheeran/asgi-ratelimit#3]
Can I have a documentation so that I can use in FastApi application? Its difficult to figure out how to use this code from given usage.

**Comment by abersheeran** [comment]
![image](https://user-images.githubusercontent.com/25364828/103228629-333f1580-496c-11eb-9bf6-5c877d832af7.png)

If need more document, please tell me which parts are needed?

**Comment by himalacharya** [comment]
> ![image](https://user-images.githubusercontent.com/25364828/103228629-333f1580-496c-11eb-9bf6-5c877d832af7.png)
> 
> If need more document, please tell me which parts are needed?

I am not clear in group ="admin"and returning user_unique_id and group_name in AUTH_FUNCTION.
Here is example how I use . Correct me if I am wrong. In main.py 

```
from app.utility.error import http422_error_handler, http_error_handler,authjwt_exception_handler
from app.utility.config import API_PREFIX, DEBUG, PROJECT_NAME, VERSION, Secret
from app.api.api_v1.api import router as api_router
from app.core.services.events import create_start_app_handler, create_stop_app_handler

from pydantic import BaseModel

from fastapi_jwt_auth import AuthJWT
from fastapi_jwt_auth.exceptions import AuthJWTException

from typing import Tuple

from ratelimit import RateLimitMiddleware, Rule
from ratelimit.auths import EmptyInformation
from ratelimit.backends.redis import RedisBackend

private_key = """
-----BEGIN RSA PRIVATE KEY-----
**********
-----END RSA PRIVATE KEY-----
"""
public_key = """
-----BEGIN PUBLIC KEY-----
***********
"""

class JwtSettings(BaseModel):
    authjwt_secret_key: str = str(Secret)
     


@AuthJWT.load_config
def get_config():
    return JwtSettings()



def get_application() -> FastAPI:
    
    application = FastAPI(title=PROJECT_NAME, debug=DEBUG, version=VERSION)

    
    application.add_event_handler(
        "startup", create_start_app_handler(application))
    application.add_event_handler(
        "shutdown", create_stop_app_handler(application))

    
    application.add_exception_handler(AuthJWTException, authjwt_exception_handler)
    application.add_exception_handler(HTTPException, http_error_handler)
    application.add_exception_handler(
        RequestValidationError, http422_error_handler)

    application.include_router(api_router, prefix=API_PREFIX)


    return application


app = get_application()


async def AUTH_FUNCTION(scope) -> Tuple[str, str]:
    """
    Resolve the user's unique identifier and the user's group from ASGI SCOPE.

    If there is no user information, it should raise `EmptyInformation`.
    If there is no group information, it should return "default".
    """
    return USER_UNIQUE_ID, GROUP_NAME

app.add_middleware(
    RateLimitMiddleware,
    authenticate=AUTH_FUNCTION,
    backend=RedisBackend(),
    config={
       
        r"^/minute_limit": [Rule(minute=1, block_time= 1), Rule(group="admin")],
    },
)
```
I tried for 1 request for 1 minute and block_time. But it doesnot limit and block my request if I made more than 1 request in a minute. Endpoint shows results of request
Main.py is called in start_server.py to run app.
My interest is to block a particular user for a minute from all endpoint if user made a request more than one in a minute.

**Comment by abersheeran** [comment]
You are not using a valid `AUTH_FUNCTION`, which requires you to parse user information and user group information from ASGI Scope. You can also use the functions in https://github.com/abersheeran/asgi-ratelimit#built-in-auth-functions.

**Comment by himalacharya** [comment]
> You are not using a valid `AUTH_FUNCTION`, which requires you to parse user information and user group information from ASGI Scope. You can also use the functions in https://github.com/abersheeran/asgi-ratelimit#built-in-auth-functions.

For auth function, I will use jwt token to fetch user_id . I am confused in this part
```
  config={
        r"^/second_limit": [Rule(second=1), Rule(group="admin")],
        r"^/minute_limit": [Rule(minute=1), Rule(group="admin")],
    },
    ```
In Rule(group), can I put "default" instead of "admin"?

**Comment by abersheeran** [comment]
Every `Rule` is a complete rule. The effect of `Rule(group="admin")` is to remove all request restrictions on users who are group admin. So if you set `Rule(group="default")`, it will remove all request restricitions on users who are group default. Maybe this is not what you want.


By the way, thanks for your reply, I think the documentation here needs to be improved.



---Original---
