### ISSUE TITLE
docs: custom block needs to be adapted

### ISSUE THREAD

**Issue by euri10** [abersheeran/asgi-ratelimit#30]
I think since the newest release 0.5.1 the https://github.com/abersheeran/asgi-ratelimit#custom-block-handler is not correct anymore. I'm not sure about it but it seems to me it has to be adapted to the new setup, at least I had to do it today at work on mine

I'll try to come up with a test and change docs when time permits if someone doesnt figure it out before L_)

**Comment by abersheeran** [comment]
Ah, this is my negligence. Thanks for pointing out.

After you test and fix the document, if you think it is okay, you only need to publish a new tag 0.5.2, and the GitHub action will automatically push the new package to PyPi.

**Comment by abersheeran** [comment]
> if you think it is okay, you only need to publish a new tag 0.5.2, and the GitHub action will automatically push the new package to PyPi.

Supplement: You can use `python script/upload.py` to ensure that `__version__.py`, `pyproject.toml` and git tags are updated at the same time.
