### ISSUE TITLE
How to resolve user/group ?

### ISSUE THREAD

**Issue by mlen108** [abersheeran/asgi-ratelimit#4]
This package looks promising, however I have little trouble understanding how to even start using it...

What/how should I resolve the user/group in `AUTH_FUNCTION` ? Sorry I don't get it from this documentation.

I also tried to use the built in `session` auth method and it fails with `AssertionError: Starlette SessionMiddleware must be installed to access request.session`

FYI using the FastApi so code looks like this:
```py
from fastapi import FastAPI
from ratelimit import RateLimitMiddleware, Rule
from ratelimit.auths.session import from_session
from ratelimit.backends.redis import RedisBackend
from starlette.middleware.sessions import SessionMiddleware

app = FastAPI()
app.add_middleware(
    SessionMiddleware,
    secret_key='aaa'
)
app.add_middleware(
    RateLimitMiddleware,
    authenticate=from_session,
    backend=RedisBackend(),
    config={
        r"^/": [Rule(second=1), Rule(group="admin")],
    },
)
```

**Comment by abersheeran** [comment]
For your code, you should reverse the order in which the two pieces of middleware were added. You must let the session middleware take effect before the ratelimit middleware.

AUTH_FUNCTION is a function for retrieving user and user group information from ASGI scope. If you don't know ASGI scope, you can refer to the [documentation](https://asgi.readthedocs.io/en/latest/specs/www.html#http-connection-scope).

**Comment by abersheeran** [comment]
Thanks for your feedback, I think I should add more tutorials. This part of the documentation is really not detailed enough.

**Comment by mlen108** [comment]
Thanks for prompt reply!

Yes, the readme could do with some basic examples to help others understand how it works.

Now I sorta get it. I thought the `scope` as of something internal of this package... I should go & read the ASGI spec first :smile: I haven't touched Python for few years & all these types / async is awesome but hard to digest at first.

**Comment by mlen108** [comment]
I closed this issue previously as I got what I wanted to eventually succeed.

I would strongly recommend that you add some more examples of what `asgi-ratelimit` is capable of doing... I almost walked away when I read the readme and it seemed to be a "basic" package. Turns out it's quite flexible...! So more examples = more happy users... ;-)

After few hours of hacking around your package & FastApi sources I came up with a code that meets my expectations (short version for simplicity).

The below is somehow an example of rate limiting based on user's subscription account that is obtained through their api-key.

```python
from typing import Tuple

from fastapi import Depends, FastAPI, Security
from fastapi.security import APIKeyQuery
from ratelimit import RateLimitMiddleware, Rule
from ratelimit.backends.redis import RedisBackend
from starlette.datastructures import QueryParams


app = FastAPI()

client_id = APIKeyQuery(name="api-key") 

async def verify_client(api_key: str = Security(client_id)):
    # needs to check if api_key exists & is allowed to use this service at all
    if api_key not in <database>:
        raise HTTPException(...)


@app.get("/", dependencies=[Depends(verify_client)])
async def whatever():
    return {...}


async def my_auth(scope: Scope) -> Tuple[str, str]:
    api_key = QueryParams(scope["query_string"])
    # perform query to database/redis to check what level of account subscription
    # is assigned to given api_key
    return api_key, <your_custom_group>


app.add_middleware(
    RateLimitMiddleware,
    authenticate=my_auth,
    backend=RedisBackend(),
    config={
        r"^/": [Rule(second=1, group="free"), Rule(second=5, block_time=100, group="basic")],
    },
)
```

Biggest surprise to me (this is *undocumented*) is that one can join rule names together with group, so one can have rate limits per time unit per group :tada: 

thanks for your amazing code :heart:

**Comment by abersheeran** [comment]
Thank you for sharing and suggestions. Compared to writing documentation, I am better at writing code. However, good advice, I will write more documents to explain how to use this library. 
By the way, if you are free, can you help me improve the documentation?
