### ISSUE TITLE
Bug when not connected to Redis

### ISSUE THREAD

**Issue by mlen108** [abersheeran/asgi-ratelimit#5]
I found a little bug.. when using the `RedisBackend` as a backend class, and when Redis is **not running** then no error will be raised in the app, but worst is that the rate limiter has no effect at all! All requests come through. Imagine my local Redis going down unexpectedly and my API becomes unlimited for everyone :scream: 

I looked at `aredis` constructor for [StrictRedis](https://github.com/NoneGG/aredis/blob/cec3cdabe67f45493ac413737d8579f46c27fded/aredis/client.py#L94) and it does not look like one can pass anything to check for available/existing connection.

Redis's official way of ensuring for connection is the [ping](https://redis.io/commands/ping) command.

I think the best solution here is to allow users to pass already established Redis connection to `backend` for `RateLimitMiddleware` ?

Or do you have a better idea?

Something like:
```python
from aredis import StrictRedis
from fastapi import FastAPI
from ratelimit import RateLimitMiddleware

app = FastAPI()
my_redis_conn = StrictRedis()

@app.on_event("startup")
async def startup():
    # either command will raise ConnectionError
    await my_redis_conn.get(None) 
    # or await my_redis_conn.ping()

app.add_middleware(
    RateLimitMiddleware,
    authenticate=my_auth,
    backend=RedisBackend(conn=my_redis_conn),
    config={
        ...
    },
)
```

With passing `my_redis_conn` we're reusing the connection - no need to make another one.

Obviously, there's some little edge case scenario. E.g. Redis & app is running, and then Redis goes down after X days & the rate limiter will again allow all requests.

So maybe it would be better to overwrite [allow_request](https://github.com/abersheeran/asgi-ratelimit/blob/e64c2737c6b3a25eb99e7c48bcc63cd86423ae6f/ratelimit/backends/base.py#L78) for Redis Backend?

**Comment by mlen108** [comment]
Okay, got thinking about it again... maybe it's not a bug and somehow an intended behaviour, however if I decide to rate limit my API then I would rather expect the service to throw error & go down as a whole than allow all requests without limits.

Which brings me to the point that this package does not need extra checks etc. But I still think that sharing a Redis connection (by passing it down to asgi-ratelimit) would be a nice addition.

**Comment by abersheeran** [comment]
In my test, after the crash of the contract, any request to pass through the flow limiter should be thrown an exception.
Can you give me a snippet of code that reproduces the bug?

**Comment by mlen108** [comment]
I'm sorry - looks like I had a bug in my own code :facepalm: It throws `ConnectionError` nicely. Closing down.
