### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by cheesycod** [abersheeran/asgi-ratelimit#6]
@abersheeran This module doesn't work when I use

app.add_middleware(
    RateLimitMiddleware,
    authenticate=client_ip,
    backend=RedisBackend(),
    config={
        r"^/": [Rule(second=1), Rule(group="admin")],
        r"^/api": [Rule(minute=1), Rule(group="admin")],
    },
)

**Comment by abersheeran** [comment]
给出更多的信息，否则我不知道你遇到了什么问题。
